In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./data/dataset.csv")

In [3]:
df

,utt_id,maya,spk_id,filename
0,spk_001_utt_0001,baach,spk_001,c5EgkTbau2o_0000
1,spk_001_utt_0002,chiich,spk_001,c5EgkTbau2o_0001
2,spk_001_utt_0003,ch'íich',spk_001,c5EgkTbau2o_0002
3,spk_001_utt_0004,ja',spk_001,c5EgkTbau2o_0003
4,spk_001_utt_0005,kool,spk_001,c5EgkTbau2o_0004
...,...,...,...,...
2530,spk_032_utt_0223,jumpuul osea ma jumpuuli cada administración p...,spk_032,15_Mario_Chan_223
2531,spk_032_utt_0224,como to'on láaj explicado to'on beeta'an to'on...,spk_032,15_Mario_Chan_224
2532,spk_032_utt_0225,le ku xkáakpachtiko'obe ma tu pak'o'obi ma tu ...,spk_032,15_Mario_Chan_225
2533,spk_032_utt_0226,teen xan man ti'ob weye camionadasil arroz kin...,spk_032,15_Mario_Chan_226
2534,spk_032_utt_0227,leten tene ya'ab ba'al juu ya'ab meyajnaja'ani...,spk_032,15_Mario_Chan_227

In [4]:
df["spk_id"].groupby(df["spk_id"]).count()

spk_id
spk_001    392
spk_002    155
spk_003     28
spk_004     28
spk_005     15
spk_006    334
spk_007     28
spk_008     29
spk_009     96
spk_010     59
spk_011     28
spk_012      5
spk_013     11
spk_014     20
spk_015     20
spk_016     20
spk_017     20
spk_018     20
spk_019     39
spk_020     38
spk_021     97
spk_022     66
spk_023     81
spk_024     43
spk_025    123
spk_026     64
spk_027     60
spk_028     31
spk_029     56
spk_030    140
spk_031    162
spk_032    227
Name: spk_id, dtype: int64

In [5]:
import shutil
from pathlib import Path

from kinai.classes.paths import Paths

repeated = {}

def copy_audio(audio_path, new_name, destination_folder):
    destination_path = destination_folder / f"{new_name}.wav"
    shutil.copy(str(audio_path), str(destination_path))
    print(f"Copied {audio_path} to {destination_path}")

folder_1h_audio = Paths().segments_folder
folder_3h_audio = Path("./3h-audios")

In [6]:
dest_audio_folder = Path("./audios")
dest_audio_folder.mkdir(parents=True, exist_ok=True)

In [7]:
for i, row in df.iterrows():
    audio_path = folder_1h_audio / f"{row['filename']}.wav"
    if audio_path.exists():
        copy_audio(str(audio_path), row["utt_id"], dest_audio_folder)
        continue

    audio_path = folder_3h_audio / f"{row['filename']}.wav"
    if audio_path.exists():
        copy_audio(str(audio_path), row["utt_id"], dest_audio_folder)
        continue
    
    print(f"file {row['filename']} does not exist")
    print(i)

Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0000.wav to audios/spk_001_utt_0001.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0001.wav to audios/spk_001_utt_0002.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0002.wav to audios/spk_001_utt_0003.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0003.wav to audios/spk_001_utt_0004.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0004.wav to audios/spk_001_utt_0005.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0005.wav to audios/spk_001_utt_0006.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0006.wav to audios/spk_001_utt_0007.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0007.wav to audios/spk_001_utt_0008.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0008.wav to audios/spk_001_utt_0009.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0009.wav to audios/spk_001_utt_0010.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0010.wav to audios/spk_001_utt_0011.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0011.wav to audios/spk_001_utt_0012.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0012.wav to audios/spk_001_utt_0013.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0013.wav to audios/spk_001_utt_0014.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0014.wav to audios/spk_001_utt_0015.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0015.wav to audios/spk_001_utt_0016.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0016.wav to audios/spk_001_utt_0017.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0017.wav to audios/spk_001_utt_0018.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0018.wav to audios/spk_001_utt_0019.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0019.wav to audios/spk_001_utt_0020.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0020.wav to audios/spk_001_utt_0021.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0021.wav to audios/spk_001_utt_0022.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0022.wav to audios/spk_001_utt_0023.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0023.wav to audios/spk_001_utt_0024.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0024.wav to audios/spk_001_utt_0025.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0025.wav to audios/spk_001_utt_0026.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0026.wav to audios/spk_001_utt_0027.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0027.wav to audios/spk_001_utt_0028.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0028.wav to audios/spk_001_utt_0029.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0029.wav to audios/spk_001_utt_0030.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0030.wav to audios/spk_001_utt_0031.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0031.wav to audios/spk_001_utt_0032.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0032.wav to audios/spk_001_utt_0033.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0033.wav to audios/spk_001_utt_0034.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0034.wav to audios/spk_001_utt_0035.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0035.wav to audios/spk_001_utt_0036.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0036.wav to audios/spk_001_utt_0037.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0037.wav to audios/spk_001_utt_0038.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0038.wav to audios/spk_001_utt_0039.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0039.wav to audios/spk_001_utt_0040.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0040.wav to audios/spk_001_utt_0041.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0041.wav to audios/spk_001_utt_0042.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0042.wav to audios/spk_001_utt_0043.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0043.wav to audios/spk_001_utt_0044.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/c5EgkTbau2o_0044.wav to audios/spk_001_utt_0045.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0000.wav to audios/spk_002_utt_0001.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0001.wav to audios/spk_002_utt_0002.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0002.wav to audios/spk_002_utt_0003.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0003.wav to audios/spk_002_utt_0004.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0004.wav to audios/spk_002_utt_0005.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0005.wav to audios/spk_002_utt_0006.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0006.wav to audios/spk_002_utt_0007.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0007.wav to audios/spk_002_utt_0008.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0008.wav to audios/spk_002_utt_0009.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0009.wav to audios/spk_002_utt_0010.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0010.wav to audios/spk_002_utt_0011.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0011.wav to audios/spk_002_utt_0012.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0012.wav to audios/spk_002_utt_0013.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0013.wav to audios/spk_002_utt_0014.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0014.wav to audios/spk_002_utt_0015.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0015.wav to audios/spk_002_utt_0016.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0016.wav to audios/spk_002_utt_0017.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0017.wav to audios/spk_002_utt_0018.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0018.wav to audios/spk_002_utt_0019.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0019.wav to audios/spk_002_utt_0020.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0020.wav to audios/spk_002_utt_0021.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0021.wav to audios/spk_002_utt_0022.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0022.wav to audios/spk_002_utt_0023.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0023.wav to audios/spk_002_utt_0024.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/VSC-pggBf2Y_0024.wav to audios/spk_002_utt_0025.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0000.wav to audios/spk_002_utt_0026.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0001.wav to audios/spk_002_utt_0027.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0002.wav to audios/spk_002_utt_0028.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0003.wav to audios/spk_002_utt_0029.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0004.wav to audios/spk_002_utt_0030.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0005.wav to audios/spk_002_utt_0031.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0006.wav to audios/spk_002_utt_0032.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0007.wav to audios/spk_002_utt_0033.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0008.wav to audios/spk_002_utt_0034.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0009.wav to audios/spk_002_utt_0035.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0010.wav to audios/spk_002_utt_0036.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0011.wav to audios/spk_002_utt_0037.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0012.wav to audios/spk_002_utt_0038.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0013.wav to audios/spk_002_utt_0039.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0014.wav to audios/spk_002_utt_0040.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0015.wav to audios/spk_002_utt_0041.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0016.wav to audios/spk_002_utt_0042.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0017.wav to audios/spk_002_utt_0043.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0018.wav to audios/spk_002_utt_0044.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0019.wav to audios/spk_002_utt_0045.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0020.wav to audios/spk_002_utt_0046.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0021.wav to audios/spk_002_utt_0047.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0022.wav to audios/spk_002_utt_0048.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0023.wav to audios/spk_002_utt_0049.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0024.wav to audios/spk_002_utt_0050.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0025.wav to audios/spk_002_utt_0051.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0026.wav to audios/spk_002_utt_0052.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0027.wav to audios/spk_002_utt_0053.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0028.wav to audios/spk_002_utt_0054.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0029.wav to audios/spk_002_utt_0055.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0030.wav to audios/spk_002_utt_0056.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0031.wav to audios/spk_002_utt_0057.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0032.wav to audios/spk_002_utt_0058.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0033.wav to audios/spk_002_utt_0059.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0034.wav to audios/spk_002_utt_0060.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0035.wav to audios/spk_002_utt_0061.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0036.wav to audios/spk_002_utt_0062.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0037.wav to audios/spk_002_utt_0063.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0038.wav to audios/spk_002_utt_0064.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0039.wav to audios/spk_002_utt_0065.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0040.wav to audios/spk_002_utt_0066.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0041.wav to audios/spk_002_utt_0067.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0042.wav to audios/spk_002_utt_0068.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0043.wav to audios/spk_002_utt_0069.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0044.wav to audios/spk_002_utt_0070.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0045.wav to audios/spk_002_utt_0071.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0046.wav to audios/spk_002_utt_0072.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0047.wav to audios/spk_002_utt_0073.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0048.wav to audios/spk_002_utt_0074.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0049.wav to audios/spk_002_utt_0075.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0050.wav to audios/spk_002_utt_0076.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0051.wav to audios/spk_002_utt_0077.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0052.wav to audios/spk_002_utt_0078.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0053.wav to audios/spk_002_utt_0079.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0054.wav to audios/spk_002_utt_0080.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0055.wav to audios/spk_002_utt_0081.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0056.wav to audios/spk_002_utt_0082.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0057.wav to audios/spk_002_utt_0083.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0058.wav to audios/spk_002_utt_0084.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0059.wav to audios/spk_002_utt_0085.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0060.wav to audios/spk_002_utt_0086.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0061.wav to audios/spk_002_utt_0087.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0062.wav to audios/spk_002_utt_0088.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0063.wav to audios/spk_002_utt_0089.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0064.wav to audios/spk_002_utt_0090.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0065.wav to audios/spk_002_utt_0091.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0066.wav to audios/spk_002_utt_0092.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0067.wav to audios/spk_002_utt_0093.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0068.wav to audios/spk_002_utt_0094.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0069.wav to audios/spk_002_utt_0095.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0070.wav to audios/spk_002_utt_0096.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0071.wav to audios/spk_002_utt_0097.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0072.wav to audios/spk_002_utt_0098.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0073.wav to audios/spk_002_utt_0099.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0074.wav to audios/spk_002_utt_0100.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0075.wav to audios/spk_002_utt_0101.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/cKlAnBXWBcg_0076.wav to audios/spk_002_utt_0102.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/J2egflaIFzk_0000.wav to audios/spk_002_utt_0103.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/J2egflaIFzk_0001.wav to audios/spk_002_utt_0104.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/J2egflaIFzk_0002.wav to audios/spk_002_utt_0105.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/J2egflaIFzk_0003.wav to audios/spk_002_utt_0106.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/J2egflaIFzk_0004.wav to audios/spk_002_utt_0107.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/J2egflaIFzk_0005.wav to audios/spk_002_utt_0108.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/J2egflaIFzk_0006.wav to audios/spk_002_utt_0109.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/J2egflaIFzk_0007.wav to audios/spk_002_utt_0110.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/J2egflaIFzk_0008.wav to audios/spk_002_utt_0111.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/J2egflaIFzk_0009.wav to audios/spk_002_utt_0112.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/J2egflaIFzk_0010.wav to audios/spk_002_utt_0113.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/J2egflaIFzk_0011.wav to audios/spk_002_utt_0114.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/J2egflaIFzk_0012.wav to audios/spk_002_utt_0115.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/J2egflaIFzk_0013.wav to audios/spk_002_utt_0116.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/J2egflaIFzk_0014.wav to audios/spk_002_utt_0117.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/J2egflaIFzk_0015.wav to audios/spk_002_utt_0118.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/J2egflaIFzk_0016.wav to audios/spk_002_utt_0119.wav
Copied /home/maucr/Documentos/thesis-mayan-ai/assets/segmented_audio/J2egflaIFzk_0017.wav to audios/spk_002_utt_0120.wav

In [8]:
df

,utt_id,maya,spk_id,filename
0,spk_001_utt_0001,baach,spk_001,c5EgkTbau2o_0000
1,spk_001_utt_0002,chiich,spk_001,c5EgkTbau2o_0001
2,spk_001_utt_0003,ch'íich',spk_001,c5EgkTbau2o_0002
3,spk_001_utt_0004,ja',spk_001,c5EgkTbau2o_0003
4,spk_001_utt_0005,kool,spk_001,c5EgkTbau2o_0004
...,...,...,...,...
2530,spk_032_utt_0223,jumpuul osea ma jumpuuli cada administración p...,spk_032,15_Mario_Chan_223
2531,spk_032_utt_0224,como to'on láaj explicado to'on beeta'an to'on...,spk_032,15_Mario_Chan_224
2532,spk_032_utt_0225,le ku xkáakpachtiko'obe ma tu pak'o'obi ma tu ...,spk_032,15_Mario_Chan_225
2533,spk_032_utt_0226,teen xan man ti'ob weye camionadasil arroz kin...,spk_032,15_Mario_Chan_226
2534,spk_032_utt_0227,leten tene ya'ab ba'al juu ya'ab meyajnaja'ani...,spk_032,15_Mario_Chan_227

In [9]:
final_df = df[["utt_id", "maya", "spk_id"]]

final_df["path"] = final_df["utt_id"].apply(lambda x: f"audios/{x}.wav")

In [10]:
final_df

,utt_id,maya,spk_id,path
0,spk_001_utt_0001,baach,spk_001,audios/spk_001_utt_0001.wav
1,spk_001_utt_0002,chiich,spk_001,audios/spk_001_utt_0002.wav
2,spk_001_utt_0003,ch'íich',spk_001,audios/spk_001_utt_0003.wav
3,spk_001_utt_0004,ja',spk_001,audios/spk_001_utt_0004.wav
4,spk_001_utt_0005,kool,spk_001,audios/spk_001_utt_0005.wav
...,...,...,...,...
2530,spk_032_utt_0223,jumpuul osea ma jumpuuli cada administración p...,spk_032,audios/spk_032_utt_0223.wav
2531,spk_032_utt_0224,como to'on láaj explicado to'on beeta'an to'on...,spk_032,audios/spk_032_utt_0224.wav
2532,spk_032_utt_0225,le ku xkáakpachtiko'obe ma tu pak'o'obi ma tu ...,spk_032,audios/spk_032_utt_0225.wav
2533,spk_032_utt_0226,teen xan man ti'ob weye camionadasil arroz kin...,spk_032,audios/spk_032_utt_0226.wav
2534,spk_032_utt_0227,leten tene ya'ab ba'al juu ya'ab meyajnaja'ani...,spk_032,audios/spk_032_utt_0227.wav

In [11]:
final_df.to_csv("./data/final_dataset.csv", index=False)

## Limpiar dataset

In [ ]:
final_df.columns

In [ ]:
from num2words import num2words
import re

def normalize_numbers(text):
    def replace_num(match):
        num = int(match.group())
        return num2words(num, lang='es')  # en español
    
    return re.sub(r'\d+', replace_num, text)

def normalize_text(text):
    # Primero números → palabras
    text = normalize_numbers(text)
    # Luego elimina los demás caracteres raros
    for char in {'$', ',', '-', '.', ':', ';', '¿'}:
        text = text.replace(char, '')
    return " ".join(text.split())

for idx, row in final_df.iterrows():
    maya = row["maya"]
    normalized = normalize_text(maya)

    if maya != normalized:
        print("-"*15)
        print(maya)
        print(normalized)
        print("-"*15)

---------------
yaan, tene' in taatae' don j poonso
yaan tene' in taatae' don j poonso
---------------
---------------
¿ba'ax bak'el a k'áatij
ba'ax bak'el a k'áatij
---------------
---------------
¿ba'ax bak'el u k'áatij
ba'ax bak'el u k'áatij
---------------
---------------
¿ba'ax bak'el u k'áat a suku'un
ba'ax bak'el u k'áat a suku'un
---------------
---------------
¿ba'ax bak'el a k'áate'ex
ba'ax bak'el a k'áate'ex
---------------
---------------
¿ba'ax bak'el u k'áato'ob
ba'ax bak'el u k'áato'ob
---------------
---------------
jsaan, ts'o'ok in taal in man tech bak'
jsaan ts'o'ok in taal in man tech bak'
---------------
---------------
wáa ma' tu chúukpajale', le buka'aj yane' ka ts'áik ten
wáa ma' tu chúukpajale' le buka'aj yane' ka ts'áik ten
---------------
---------------
kex chéen, je'el a chúukpesik ten yéetel uláak' bak'e'
kex chéen je'el a chúukpesik ten yéetel uláak' bak'e'
---------------
---------------
tu ts'aj tech uts, jach ka'a p'éel kiilo yani'
tu ts'aj tech uts jach ka'a p'éel kiilo yani'
---------------
---------------
$50 pesos, tumeen jun p'éel kiiloe' $25
cincuenta pesos tumeen jun p'éel kiiloe' veinticinco
---------------
---------------
ma' ko'oji'; jo'e' maas ko'oj
ma' ko'oji' jo'e' maas ko'oj
---------------
---------------
jaach jaaj: je'el a wo'och bak'a'
jaach jaaj je'el a wo'och bak'a'
---------------
---------------
je'el xan le $50 pesosa'; ma'alob, dios bo'otik
je'el xan le cincuenta pesosa' ma'alob dios bo'otik
---------------
---------------
ma'alob, mix ba'al
ma'alob mix ba'al
---------------
---------------
teen, teech yéetel jraache' taak k ts'o'oksike'ex le meyajo'
teen teech yéetel jraache' taak k ts'o'oksike'ex le meyajo'
---------------
---------------
utia'al ka'aj páajchak u bin u yilej.
utia'al ka'aj páajchak u bin u yilej
---------------
---------------
bix a beel, xunáan
bix a beel xunáan
---------------
---------------
jkalinen, in chiich xmáaj kooncha
jkalinen in chiich xmáaj kooncha
---------------
---------------
jaaj, leti'
jaaj leti'
---------------
---------------
tene' jo' kaja'anen, tu yo'olal le je'elo' yáax a wilikena'
tene' jo' kaja'anen tu yo'olal le je'elo' yáax a wilikena'
---------------
---------------
kux túun a maama yéetel a yuum, máaxo'ob
kux túun a maama yéetel a yuum máaxo'ob
---------------
---------------
in maamae' xmáaj meech, in taatae' don jpoonso
in maamae' xmáaj meech in taatae' don jpoonso
---------------
---------------
in k'aj óolo'ob, ba'ale' úuch in wilo'ob, tu'ux yano'ob beya'
in k'aj óolo'ob ba'ale' úuch in wilo'ob tu'ux yano'ob beya'
---------------
---------------
tia'ano'ob ítsmale', ti' kaja'ano'obi'
tia'ano'ob ítsmale' ti' kaja'ano'obi'
---------------
---------------
jaaj a t'aan, ti' kaja'ano'obi', bix u beelo'ob
jaaj a t'aan ti' kaja'ano'obi' bix u beelo'ob
---------------
---------------
ma'alob, toj u yóolo'ob; bix túun a k'aaba' xunáan
ma'alob toj u yóolo'ob bix túun a k'aaba' xunáan
---------------
---------------
xdóomitila in k'aaba', chéen ba'ale' xtiila u ya'ala'al tene
xdóomitila in k'aaba' chéen ba'ale' xtiila u ya'ala'al tene
---------------
---------------
jsaan u k'aaba', ba'ale' ma' in wojel tu'ux kaja'ani'
jsaan u k'aaba' ba'ale' ma' in wojel tu'ux kaja'ani'
---------------
---------------
ma' in wojel máakalmáak le ka wa'alik techo', máax u yuum
ma' in wojel máakalmáak le ka wa'alik techo' máax u yuum
---------------
---------------
chéen ba'ax in wojele'
chéen ba'ax in wojele'
---------------
---------------
wáa beyo' in wojel máaxi', ma' jach náach ti' in wotoch kaja'ani'
wáa beyo' in wojel máaxi' ma' jach náach ti' in wotoch kaja'ani'
---------------
---------------
ka tséelel ta no'oj, jach míij tu yóok'ol óoxp'éel naje' ti'i'
ka tséelel ta no'oj jach míij tu yóok'ol óoxp'éel naje' ti'i'
---------------
---------------
jump'éel ya'ax pak'il naj, ma' jach nojochi'
jump'éel ya'ax pak'il naj ma' jach nojochi'
---------------
---------------
ma' ta sa'atal, chéen ch'a'abil, u yuume' yuum jmiilo
ma' ta sa'atal chéen ch'a'abil u yuume' yuum jmiilo
---------------
---------------
beyi'istako'; aktáan ti' u yotoch le yuum jmiiloo' ti kaja'an in wáabil jleexoi'
beyi'istako' aktáan ti' u yotoch le yuum jmiiloo' ti kaja'an in wáabil jleexoi'
---------------
---------------
beyo', tene' ook'in in bin xíimbalt in wáabil, tumeen úuch in wilej
beyo' tene' ook'in in bin xíimbalt in wáabil tumeen úuch in wilej
---------------
---------------
ma'alob túun xunáan, jach ya'abkach dios bo'otik
ma'alob túun xunáan jach ya'abkach dios bo'otik
---------------
---------------
ma'alob, nika'aj in wil le jsaano'
ma'alob nika'aj in wil le jsaano'
---------------
---------------
wáa beyo', in wojel
wáa beyo' in wojel
---------------
---------------
wáa beyo', a wojel tu'uxi'
wáa beyo' a wojel tu'uxi'
---------------
---------------
wáa beyo', u yojel máaxi'
wáa beyo' u yojel máaxi'
---------------
---------------
wáa beyo', k ojel bixij
wáa beyo' k ojel bixij
---------------
---------------
wáa beyo', a wojele'ex máakalmáak
wáa beyo' a wojele'ex máakalmáak
---------------
---------------
wáa beyo', u yojelo'ob ba'axi'
wáa beyo' u yojelo'ob ba'axi'
---------------
---------------
wáa beyo', jkaline' u yojel bajux
wáa beyo' jkaline' u yojel bajux
---------------
---------------
wáa beyo', k ojel ba'axten
wáa beyo' k ojel ba'axten
---------------
---------------
wáa beyo', a k'aj óolene'ex
wáa beyo' a k'aj óolene'ex
---------------
---------------
jsaan, jsaan kula'anech wáa
jsaan jsaan kula'anech wáa
---------------
---------------
ma' kula'ani, bija'an tu yiknal in kiik xmaruch
ma' kula'ani bija'an tu yiknal in kiik xmaruch
---------------
---------------
chan sáamij, te'eytak u suut wale'
chan sáamij te'eytak u suut wale'
---------------
---------------
taak in páa'tik lo'obal, ba'ale' kux túun wáa ku xáantal nal a kiiko'
taak in páa'tik lo'obal ba'ale' kux túun wáa ku xáantal nal a kiiko'
---------------
---------------
máax yéetel ka tsikbal, xch'úupal
máax yéetel ka tsikbal xch'úupal
---------------
---------------
a'al ti' ka'aj máanak, ma' tu xáantal ts'o'ok u k'uchul
a'al ti' ka'aj máanak ma' tu xáantal ts'o'ok u k'uchul
---------------
---------------
ma'alob, je'el le k'áanche'o', kuleen
ma'alob je'el le k'áanche'o' kuleen
---------------
---------------
dios bo'otik, tene' jkalin in k'aaba', in taatae' don jpoonso witsíil, ma' in wojel wáa a k'aj óoli'
dios bo'otik tene' jkalin in k'aaba' in taatae' don jpoonso witsíil ma' in wojel wáa a k'aj óoli'
---------------
---------------
bix ma' in k'aj óoltik, in wéet xook ka'ach úuchij
bix ma' in k'aj óoltik in wéet xook ka'ach úuchij
---------------
---------------
chéen beya', ma' ta wa'alaj ten wáa yaan a taali'
chéen beya' ma' ta wa'alaj ten wáa yaan a taali'
---------------
---------------
ts'o'ok in taal kex chéen junsúutuk, bix túun u beel a kiiko'
ts'o'ok in taal kex chéen junsúutuk bix túun u beel a kiiko'
---------------
---------------
ma' jach ma'alobi', táan u chi'ibal u pool
ma' jach ma'alobi' táan u chi'ibal u pool
---------------
---------------
xuulul, ba'ale' táan u chan máan kex beyo'
xuulul ba'ale' táan u chan máan kex beyo'
---------------
---------------
mina'an, chéen in suku'un yaan
mina'an chéen in suku'un yaan
---------------
---------------
jkalin. chéen ka'atúul
jkalin chéen ka'atúul
---------------
---------------
juntúule' jpiil yéetel uláak'o' je'e bix u k'aaba' in taatao', ba'ale' jach jela'antako'ob
juntúule' jpiil yéetel uláak'o' je'e bix u k'aaba' in taatao' ba'ale' jach jela'antako'ob
---------------
---------------
le jpoonsoo' chíika'an ti' in maama, mulix, kaabal u bakel
le jpoonsoo' chíika'an ti' in maama mulix kaabal u bakel
---------------
---------------
bek'ech, ts'o'okole' ya'axtak u yich
bek'ech ts'o'okole' ya'axtak u yich
---------------
---------------
leti'e' maas chan chíika'an ti' in taata, polok, ka'anal u bakel
leti'e' maas chan chíika'an ti' in taata polok ka'anal u bakel
---------------
---------------
piim u me'ex, le ku ts'o'okole' ch'eel xan
piim u me'ex le ku ts'o'okole' ch'eel xan
---------------
---------------
je'elo' jaaj a t'aan, jach jela'antako'ob. teche' chan chíika'anech ti' tu ka'atúulil
je'elo' jaaj a t'aan jach jela'antako'ob teche' chan chíika'anech ti' tu ka'atúulil
---------------
---------------
ka'anal a baakel, bek'echech, k'as mulixech, yaan xan a me'ex
ka'anal a baakel bek'echech k'as mulixech yaan xan a me'ex
---------------
---------------
tene' jach uts tin wich in cha'antik le pay wakaxo'...
tene' jach uts tin wich in cha'antik le pay wakaxo'
---------------
---------------
kin cha'antik, ba'ale' ma' tin wóok'ostik
kin cha'antik ba'ale' ma' tin wóok'ostik
---------------
---------------
tumeen chéen ko'olel uts tin wich, ja, ja, ja lelo' tak teen
tumeen chéen ko'olel uts tin wich ja ja ja lelo' tak teen
---------------
---------------
ma'alobe'ex túun, táan in bin tiknal in chiich, ts'o'ok in wi'ijtal
ma'alobe'ex túun táan in bin tiknal in chiich ts'o'ok in wi'ijtal
---------------
---------------
wáa wi'ijeche' p'áaten janal, mix jaanko'on xani'
wáa wi'ijeche' p'áaten janal mix jaanko'on xani'
---------------
---------------
ma'alob xi'ipal, kaláantaba
ma'alob xi'ipal kaláantaba
---------------
---------------
bix túun, yaan wáa a jóok'ol ka'akate'
bix túun yaan wáa a jóok'ol ka'akate'
---------------
---------------
míij ma'. saabadoe' yaan k bin xíimbalt xmáaj tiila
míij ma' saabadoe' yaan k bin xíimbalt xmáaj tiila
---------------
---------------
je'ele, kex ba'ax oora
je'ele kex ba'ax oora
---------------
---------------
je'elo' bey k p'áatalo', ma'alob
je'elo' bey k p'áatalo' ma'alob
---------------
---------------
ma'alob, tak saabado
ma'alob tak saabado
---------------
---------------
kin wóok'ostik, ba'ale' ma' tin k'ayik
kin wóok'ostik ba'ale' ma' tin k'ayik
---------------
---------------
ka xokik, ba'ale' ma' ta ts'íibtik
ka xokik ba'ale' ma' ta ts'íibtik
---------------
---------------
ku k'ayik, ba'ale' ma' tu paxik
ku k'ayik ba'ale' ma' tu paxik
---------------
---------------
k wenel, ba'ale' ma' t náay
k wenel ba'ale' ma' t náay
---------------
---------------
k tuklike'ex, ba'ale' ma' t beetke'ex
k tuklike'ex ba'ale' ma' t beetke'ex
---------------
---------------
lep' a wóol, xi'ipal
lep' a wóol xi'ipal
---------------
---------------
ko'ox, ta juunal wáa taalech
ko'ox ta juunal wáa taalech
---------------
---------------
tin juunal, ma' taal in maama mix in taatai', p'áato'ob íitsmal wale'
tin juunal ma' taal in maama mix in taatai' p'áato'ob íitsmal wale'
---------------
---------------
ko'ox, naats' u yotoch le xmáaj tiilao'
ko'ox naats' u yotoch le xmáaj tiilao'
---------------
---------------
yéetel juntúul u yáabil, jach ki'ichpam
yéetel juntúul u yáabil jach ki'ichpam
---------------
---------------
ts'okan ka'achij, ba'ale' kimeen u yíicham
ts'okan ka'achij ba'ale' kimeen u yíicham
---------------
---------------
mina'an, ma' úuch ts'o'okok u beelo'ob ka'achi'
mina'an ma' úuch ts'o'okok u beelo'ob ka'achi'
---------------
---------------
ma' tak be'ooraa' ma', ba'ale' ma' k ojel wáa ichil jump'íit k'iine'
ma' tak be'ooraa' ma' ba'ale' ma' k ojel wáa ichil jump'íit k'iine'
---------------
---------------
ku ka' ts'o'okol u beel tu ka'a téen, ba'axten
ku ka' ts'o'okol u beel tu ka'a téen ba'axten
---------------
---------------
chéen tumen; buka'aj u bin k kóojol
chéen tumen buka'aj u bin k kóojol
---------------
---------------
xmáaj tiila, ba'ax ka beetik beya'
xmáaj tiila ba'ax ka beetik beya'
---------------
---------------
táan in jóoyabtil in paak'al, taalo'ob wáa a yuum yéetel a maamao'
táan in jóoyabtil in paak'al taalo'ob wáa a yuum yéetel a maamao'
---------------
---------------
ma' taalo'obi'. xmáaj tiila, chéen taalen in wa'al teche' bejla'ab in bin íitsmale'
ma' taalo'obi' xmáaj tiila chéen taalen in wa'al teche' bejla'ab in bin íitsmale'
---------------
---------------
lep' a wóol túuni', te'eytak u máan le waawáo'
lep' a wóol túuni' te'eytak u máan le waawáo'
---------------
---------------
ma'alob, pa'atik in bin
ma'alob pa'atik in bin
---------------
---------------
wáa ba'axe' tak juulio wale', je'el in taal in xíimbalteche'
wáa ba'axe' tak juulio wale' je'el in taal in xíimbalteche'
---------------
---------------
ma', yéetel in wáabil, ma' bakáan ta k'aj óoltaji'
ma' yéetel in wáabil ma' bakáan ta k'aj óoltaji'
---------------
---------------
mixba'al ti'e', je'elili' in k'aj óoltik le kéen suunakene'
mixba'al ti'e' je'elili' in k'aj óoltik le kéen suunakene'
---------------
---------------
ma'alob túun, xi'ikech yéetel ya'abkach uts
ma'alob túun xi'ikech yéetel ya'abkach uts
---------------
---------------
ma'alob, bix ma'il, ti' kin in páa'techi'
ma'alob bix ma'il ti' kin in páa'techi'
---------------
---------------
ma'alob túun, je'el ku taal le waawáo'
ma'alob túun je'el ku taal le waawáo'
---------------
---------------
bey túuno', jkaline' na'ak te' waawáo' ka'aj bin íitsmal.
bey túuno' jkaline' na'ak te' waawáo' ka'aj bin íitsmal
---------------
---------------
anchaj u p'atik máaxo'ob tu k'aj óoltaj tu kaajil k'íimbila';
anchaj u p'atik máaxo'ob tu k'aj óoltaj tu kaajil k'íimbila'
---------------
---------------
ba'ale' ki'imak xan u yóol tumen tu k'aj óoltaj le kaajo',
ba'ale' ki'imak xan u yóol tumen tu k'aj óoltaj le kaajo'
---------------
---------------
chéen juntúulili' máax tu bineltaj u k'aj óoltik: u yáabil xmáaj tiila,
chéen juntúulili' máax tu bineltaj u k'aj óoltik u yáabil xmáaj tiila
---------------
---------------
ba'ale' tu ya'alal yaan u béeytal, le kéen suunak
ba'ale' tu ya'alal yaan u béeytal le kéen suunak
---------------
---------------
bejla'ab túune' jkaline' óoxp'éel u kaajal yaan: jo', íitsmal yéetel k'íimbila'.
bejla'ab túune' jkaline' óoxp'éel u kaajal yaan jo' íitsmal yéetel k'íimbila'
---------------
---------------
je'el k-ilikba'e'
je'el kilikba'e'
---------------
---------------
je'el k-ilikba'e'
je'el kilikba'e'
---------------
---------------
je'el k-ilikba'e'
je'el kilikba'e'
---------------
---------------
je'el k-ilikba'e'
je'el kilikba'e'
---------------
---------------
je'el k-ilikba'e'
je'el kilikba'e'
---------------
---------------
pues komo ma u yojel máake ka wa'alik ti'e  pues oken ko'oten le káan weenekeche
pues komo ma u yojel máake ka wa'alik ti'e pues oken ko'oten le káan weenekeche
---------------
---------------
de le xchi'ichi'ibejo le ku jit'ik beya ku beetik jump'éel suume pero yaan u payalchi'il ikil u ya'alik bey uti'al u meentiko ka tu ya'alaje  pues tene yaan in chukik le ko'olelo
de le xchi'ichi'ibejo le ku jit'ik beya ku beetik jump'éel suume pero yaan u payalchi'il ikil u ya'alik bey uti'al u meentiko ka tu ya'alaje pues tene yaan in chukik le ko'olelo
---------------
---------------
ka tu yilaj ma tu yutstal u kotsik le suumo ka jo'op u yok'ol tu táan le máako ka tu ya'alaj ti'e  ba'axten ka meentik teen beya ma waáj ta wilike tene
ka tu yilaj ma tu yutstal u kotsik le suumo ka jo'op u yok'ol tu táan le máako ka tu ya'alaj ti'e ba'axten ka meentik teen beya ma waáj ta wilike tene
---------------
---------------
juan t'u'ul leéken a tsikbalto jaaj  je'elo le chan konejoo le xnuk kojo ka jo'op u taal u taal te bejo
juan t'u'ul leéken a tsikbalto jaaj je'elo le chan konejoo le xnuk kojo ka jo'op u taal u taal te bejo
---------------
---------------
ka enkontrarta'ab tumen le chan t'u'ulo leti le chan t'u'ulo xíimbalil u taal ku ya'ala'al bin ti'e  tu'un ka bin  tene chéen tin máan  ki bin  kux túun teech  tene te chak'an kin bina  ki bin  nika'aj in
ka enkontrarta'ab tumen le chan t'u'ulo leti le chan t'u'ulo xíimbalil u taal ku ya'ala'al bin ti'e tu'un ka bin tene chéen tin máan ki bin kux túun teech tene te chak'an kin bina ki bin nika'aj in
---------------
---------------
wil in mejen paalal in p'atmaji ku chan a'alik bin óotsil xnuk koj  je'elo ko'ox  pues si ma tu yutstal in taal  ki bin  wa ka a ki kuchene je k bine  ki bin  je'elo ma'alob  ki bin
wil in mejen paalal in p'atmaji ku chan a'alik bin óotsil xnuk koj je'elo ko'ox pues si ma tu yutstal in taal ki bin wa ka a ki kuchene je k bine ki bin je'elo ma'alob ki bin
---------------
---------------
ku ya'alik bine  je wáaj a ki bisik teen jump'éel karga aake  ki bin  uti'al in meentik in chan taanaj uti'al in mejen paalal  ku chan a'alik bin le chan konejoo  le aako xíiwul xíiw wáaj sakate ba'ax  jaaj je'elo ka jo'op ku ya'alik bine  ma táan  ki bin
ku ya'alik bine je wáaj a ki bisik teen jump'éel karga aake ki bin uti'al in meentik in chan taanaj uti'al in mejen paalal ku chan a'alik bin le chan konejoo le aako xíiwul xíiw wáaj sakate ba'ax jaaj je'elo ka jo'op ku ya'alik bine ma táan ki bin
---------------
---------------
bueno ki bis teen  ki bin  bueno bix túun kéen k meentej  pues yaan in k'axik ta pu'uch  ku ya'ala'al bin ka bin k'a'ax yéetel aak aak jóol wáaj ba'ax ken u kaxt beyo ku k'axaj ka síit'naje
bueno ki bis teen ki bin bueno bix túun kéen k meentej pues yaan in k'axik ta pu'uch ku ya'ala'al bin ka bin k'a'ax yéetel aak aak jóol wáaj ba'ax ken u kaxt beyo ku k'axaj ka síit'naje
---------------
---------------
jaan ka síit'naje tu pu'uch le xnuk kojo ka jo'op u bino'ob ku ya'alik bine  wa ka a ki cha'e jin ts'u'uts'e  ki bin  táaj taak in ts'u'uts  ki bin  mare ma táan  ki bin  bik a tóoken  ki bin  ma  ki bin
jaan ka síit'naje tu pu'uch le xnuk kojo ka jo'op u bino'ob ku ya'alik bine wa ka a ki cha'e jin ts'u'uts'e ki bin táaj taak in ts'u'uts ki bin mare ma táan ki bin bik a tóoken ki bin ma ki bin
---------------
---------------
ka ki ok leti'i ka jo'op u ya'alik beyo  je'abáaj ts'arbay nup'abáaj ts'arbay je'abáaj ts'arbay ti ki ch'uya'ani ku ya'alik bin le óotsil xnuk kojo  je'el in puuts'o  ki bin  leti lela  ki bin
ka ki ok leti'i ka jo'op u ya'alik beyo je'abáaj ts'arbay nup'abáaj ts'arbay je'abáaj ts'arbay ti ki ch'uya'ani ku ya'alik bin le óotsil xnuk kojo je'el in puuts'o ki bin leti lela ki bin
---------------
---------------
taal bine ku ya'alik bine  ba'an ka kaxtik te'elo  ku ya'ala'al bin  mixba'al  ki bin  dios tene desde ku ts'a'abal yóok'ol kaab weye kaj ki ts'a'aben te'ela tene tia'aneni  aah ma jaaji  ki bin
taal bine ku ya'alik bine ba'an ka kaxtik te'elo ku ya'ala'al bin mixba'al ki bin dios tene desde ku ts'a'abal yóok'ol kaab weye kaj ki ts'a'aben te'ela tene tia'aneni aah ma jaaji ki bin
---------------
---------------
teech le ta tóokene  ki bin je'elo ka bin ka bin a'ala'ab ti beyo je'elo  oken ka kan le k'aay kin meentika  ki bin ka jo'op u k'aay xan
teech le ta tóokene ki bin je'elo ka bin ka bin a'ala'ab ti beyo je'elo oken ka kan le k'aay kin meentika ki bin ka jo'op u k'aay xan
---------------
---------------
je'elo ts'a kanik pa'at in jáan bin janal oora kin suute  ki bin aay dios óotsil xnuk koje kaj ki p'áatij
je'elo ts'a kanik pa'at in jáan bin janal oora kin suute ki bin aay dios óotsil xnuk koje kaj ki p'áatij
---------------
---------------
tia'ani tia'ani ma wáaj bin ka tu'ub ti bine ku ya'alik bine  nup'abáaj ts'arbay nup'abáaj ts'arbay ku yu'ub bine ts'o'okij tu je'ep'el ku ya'alik bine  bix túun ken in ki meentik dios mío  ki bin
tia'ani tia'ani ma wáaj bin ka tu'ub ti bine ku ya'alik bine nup'abáaj ts'arbay nup'abáaj ts'arbay ku yu'ub bine ts'o'okij tu je'ep'el ku ya'alik bine bix túun ken in ki meentik dios mío ki bin
---------------
---------------
ku chéen kulukbal bey te ich le ba'axo je'elo k'a'aj túun ti bin beyo ka jo'op u ya'alik  je'abáaj ts'arbay je'abáaj ts'arbay je'abáaj ts'arbay ka bin tu yilaje ts'o'okij chan jóok u yáalkab bine dios bin tu meentaj
ku chéen kulukbal bey te ich le ba'axo je'elo k'a'aj túun ti bin beyo ka jo'op u ya'alik je'abáaj ts'arbay je'abáaj ts'arbay je'abáaj ts'arbay ka bin tu yilaje ts'o'okij chan jóok u yáalkab bine dios bin tu meentaj
---------------
---------------
jay leti le in puuts'o  ki bin ok bin te sajkabo  yaan in jaantik bejla'e  ki bin ok te sajkab bino ka bin  hola juanito  ku ya'ala'al bin  teech le ta tusene  ku ya'alik

In [40]:
final_df_clean = final_df.copy()
final_df_clean["maya"] = final_df_clean["maya"].apply(normalize_text)

In [41]:
final_df_clean

,utt_id,maya,spk_id,path
0,spk_001_utt_0001,baach,spk_001,audios/spk_001_utt_0001.wav
1,spk_001_utt_0002,chiich,spk_001,audios/spk_001_utt_0002.wav
2,spk_001_utt_0003,ch'íich',spk_001,audios/spk_001_utt_0003.wav
3,spk_001_utt_0004,ja',spk_001,audios/spk_001_utt_0004.wav
4,spk_001_utt_0005,kool,spk_001,audios/spk_001_utt_0005.wav
...,...,...,...,...
2530,spk_032_utt_0223,jumpuul osea ma jumpuuli cada administración p...,spk_032,audios/spk_032_utt_0223.wav
2531,spk_032_utt_0224,como to'on láaj explicado to'on beeta'an to'on...,spk_032,audios/spk_032_utt_0224.wav
2532,spk_032_utt_0225,le ku xkáakpachtiko'obe ma tu pak'o'obi ma tu ...,spk_032,audios/spk_032_utt_0225.wav
2533,spk_032_utt_0226,teen xan man ti'ob weye camionadasil arroz kin...,spk_032,audios/spk_032_utt_0226.wav
2534,spk_032_utt_0227,leten tene ya'ab ba'al juu ya'ab meyajnaja'ani...,spk_032,audios/spk_032_utt_0227.wav

In [49]:
final_df_clean.to_csv("./data/final_dataset_clean.csv")